### ISSUE TITLE
ES module error on Node.js 13

### ISSUE THREAD

**Issue by TyLindberg** [CesiumGS/gltf-pipeline#507]
When running the tests using node v13.3.0 the following error is thrown.

```
Warning: require() of ES modules is not supported.
require() of /Users/tylerlindberg/repos/forks/gltf-pipeline/node_modules/cesium/index.js from /Users/tylerlindberg/repos/forks/gltf-pipeline/gulpfile.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/tylerlindberg/repos/forks/gltf-pipeline/node_modules/cesium/package.json.
```

It seems like an error due to Cesium's recent upgrade to using ES6 modules in v1.63, as manually setting the package to v1.62.0 causes the tests to run successfully.

In Node versions 12 and below this error doesn't occur

**Comment by lilleyse** [comment]
Looks like the same issue in `obj2gltf` which also includes cesium - https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/225.

@mramato do you know the best way to fix this?

**Comment by mramato** [comment]
This actually looks like a breaking change introduced in Node 13, everything works on 10 and 12.  I'll have to do a little research to figure out the right path forward.  @lilleyse can you write up an issue in Cesium about Node 13 support and link the other two issues?  Tag it `next release` so we get it into Jan 2nd.

**Comment by lilleyse** [comment]
Here's the cesium issue: https://github.com/AnalyticalGraphicsInc/cesium/issues/8452

**Comment by md2perpe** [comment]
I get this warning also in node v12.13.1:

> node version: v12.13.1
> (node:99307) Warning: require() of ES modules is not supported.
> require() of /home/ingrid/PostProcessing/production/20200123T193215/node_modules/cesium/index.js from /home/ingrid/PostProcessing/production/20200123T193215/node_modules/gltf-pipeline/bin/gltf-pipeline.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
> Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/ingrid/PostProcessing/production/20200123T193215/node_modules/cesium/package.json.
>

**Comment by Giorat** [comment]
I solved this issue by running node v12.0.0

**Comment by AlexPiro** [comment]
Do anyone worked on this problem ? Changing node version of the project is not a solution ! As noticed by @md2perpe the problem also exists in some version of Node v12 so it is not v13 only related.

**Comment by mramato** [comment]
@AlexPiro there's a PR into Cesium to fix this that should go out with it's next release: https://github.com/CesiumGS/cesium/pull/8659 (April 1)

We just need to do some additional review/testing on it.

**Comment by edsilv** [comment]
If I try converting a glb to draco using node v12.0.0 I get `Error: Cannot find module './freezeObject.js'`

**Comment by lilleyse** [comment]
@edsilv you might need to run `npm install` to get the latest cesium version.

**Comment by lilleyse** [comment]
CesiumJS 1.68.0 was released yesterday with the fix. I tested that gltf-pipeline now works with Node 13.12.0.
